sudo: required
language: java
dist: trusty
jdk:
- openjdk8
install: true # skips travis' default installation step which executes gradle assemble.
script: ./gradlew clean build
# The before_cache and the cache steps cache the gradle installation on travis.
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
#- bash <(curl -s https://codecov.io/bash) TODO: GITHUB ISSUE#3
- ./travis-publish.sh || travis_terminate 1
notifications:
  hipchat:
    template:
    - '<b><a href="https://github.com/commercetools/project-coeur-sync">%{repository}</a></b>
    #<a href="%{build_url}">%{build_number}</a>
    <br>(%{branch} - <a href="%{compare_url}">%{commit}</a> : %{author}): <b>%{message}</b>
      <br><b>Build duration:</b> %{duration}.'
    format: html
    on_pull_requests: false
    on_success: change
    on_failure: always
    rooms:
      secure: #todo should be added
