version: 1
update_configs:
  - package-ecosystem: docker
    directory: /
    update_schedule: "weekly"
      
  - package_manager: java:gradle
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "*"
